'use client';

import { useEffect, useMemo, useRef, useState } from 'react';

type Asset = '黄金' | '白银' | '铜' | '锡' | '原油' | '美元' | '大豆' | '玉米' | '螺纹钢';
type Event = { id:number; asset:Asset; side:'利多'|'利空'; title:string; summary:string; source:string; sourceUrl:string; publishedAt:string; time:string; impact:number; confidence:number; tags:string[] };
type Snapshot = { symbol?:string; name?:string; price:number; change_pct?:number|null; provider:string; data_mode:string; delayed?:boolean; as_of?:string; source_url?:string; freshness?:string };
type WeekEvent = { id:number; date:string; window:'过去7天'|'未来7天'; side:'利多'|'利空'|'中性'; impact:'高'|'中'; title:string; assets:string; why:string; source:string; sourceUrl:string };
type ImageMeta = { file_name:string; mime_type:string; size_bytes:number; width:number; height:number };
type ImageAnalysis = { provider:string; mode:string; title:string; conclusion:string; signals:string[]; next:string; received?:boolean; analysis_status?:string; received_at?:string };
type ImageStatus = 'idle'|'loading'|'ready'|'analyzing'|'done'|'error';
type BoardSync = { status:string; synced_at?:string; latency_ms?:number; refresh_mode?:string; cache_ttl_seconds?:number; live_count?:number; item_count?:number };

/** The sidebar/quick switcher intentionally contains only the six primary markets.
 * Other supported assets remain searchable from the global search box. */
const focusAssets: Asset[] = ['黄金','白银','铜','锡','原油','美元'];
const assets: Record<Asset, {symbol:string; price:string; change:string; score:number; tone:string}> = {
  黄金:{symbol:'GC / AU',price:'2,654.80',change:'+1.28%',score:72,tone:'偏多'},
  白银:{symbol:'SI / AG',price:'31.642',change:'+0.86%',score:64,tone:'震荡偏多'},
  铜:{symbol:'HG / CU',price:'9,842.50',change:'+0.34%',score:58,tone:'中性'},
  锡:{symbol:'SN / LME',price:'256,780',change:'-0.42%',score:43,tone:'中性偏空'},
  原油:{symbol:'CL / WTI',price:'78.420',change:'-0.67%',score:47,tone:'震荡偏空'},
  美元:{symbol:'DXY / USD',price:'103.42',change:'-0.18%',score:52,tone:'中性'},
  大豆:{symbol:'ZS / CBOT',price:'1,018.25',change:'+0.22%',score:54,tone:'中性'},
  玉米:{symbol:'ZC / CBOT',price:'412.75',change:'-0.18%',score:49,tone:'中性'},
  螺纹钢:{symbol:'RB / SHFE',price:'3,462',change:'-0.31%',score:45,tone:'中性偏空'},
};
const assetContext:Record<Asset,{range:string;catalyst:string;risk:string;verify:string}>={
 黄金:{range:'2,621.80 – 2,661.30',catalyst:'实际利率继续回落',risk:'高位拥挤与非农超预期',verify:'非农 + ETF 流向'},白银:{range:'31.08 – 31.86',catalyst:'金银比回落与工业需求改善',risk:'库存累积与波动放大',verify:'COMEX 库存 + 金银比'},铜:{range:'9,760 – 9,930',catalyst:'中国制造业需求回升',risk:'美元走强与库存累积',verify:'中国 PMI + LME 库存'},锡:{range:'254,000 – 259,800',catalyst:'矿端扰动与库存去化',risk:'下游订单恢复偏慢',verify:'LME / 中国库存'},原油:{range:'77.60 – 79.20',catalyst:'供给收缩与库存下降',risk:'需求走弱与意外累库',verify:'EIA 库存 + OPEC+'},美元:{range:'102.60 – 104.20',catalyst:'美国数据走弱与降息预期升温',risk:'美国数据超预期与实际利率上行',verify:'DXY + 美债实际利率'},大豆:{range:'1,000 – 1,032',catalyst:'天气扰动与出口改善',risk:'天气改善与出口走弱',verify:'USDA + 天气'},玉米:{range:'405 – 422',catalyst:'天气扰动或出口超预期',risk:'产量上修与库存累积',verify:'USDA + 天气'},螺纹钢:{range:'3,380 – 3,520',catalyst:'库存去化与基建回升',risk:'需求疲弱与库存反弹',verify:'钢材库存 + 基建数据'}
};
const events: Event[] = [
 {id:1,asset:'黄金',side:'利多',title:'美债实际收益率回落，避险资金回流黄金',summary:'美元与实际利率同步走弱，黄金资金流出现连续净流入。若非农预期进一步下修，金价上行动能或延续。',source:'Reuters',sourceUrl:'https://www.reuters.com/markets/commodities/',publishedAt:'2026-09-03T09:42:00+08:00',time:'09:42',impact:92,confidence:88,tags:['宏观','资金流','跨源验证']},
 {id:2,asset:'黄金',side:'利空',title:'高位获利了结增多，期权波动率抬升',summary:'短周期持仓拥挤度进入警戒区，2,670附近或面临技术性抛压。',source:'CME Group',sourceUrl:'https://www.cmegroup.com/markets/metals/precious/gold.html',publishedAt:'2026-09-03T08:55:00+08:00',time:'08:55',impact:68,confidence:76,tags:['技术面','期权']},
 {id:3,asset:'白银',side:'利多',title:'光伏需求预期改善，现货升水扩大',summary:'工业需求边际转强叠加贵金属共振，白银弹性高于黄金，但波动风险也同步放大。',source:'Silver Institute',sourceUrl:'https://silverinstitute.org/silver-supply-demand/',publishedAt:'2026-09-03T10:06:00+08:00',time:'10:06',impact:84,confidence:81,tags:['产业链','现货']},
 {id:4,asset:'白银',side:'利空',title:'交易所库存周度回升',summary:'可交割库存止降回升，短期缓解供应偏紧预期，限制价格追涨空间。',source:'COMEX',sourceUrl:'https://www.cmegroup.com/markets/metals/precious/silver.html',publishedAt:'2026-09-03T07:48:00+08:00',time:'07:48',impact:61,confidence:83,tags:['库存','供需']},
 {id:5,asset:'锡',side:'利多',title:'主要产区供应扰动预期升温',summary:'矿端审批与雨季运输扰动可能造成阶段性缺口，冶炼端加工费仍处低位。',source:'SMM',sourceUrl:'https://news.metal.com/',publishedAt:'2026-09-03T09:18:00+08:00',time:'09:18',impact:79,confidence:72,tags:['供应','矿端']},
 {id:6,asset:'锡',side:'利空',title:'下游电子订单恢复仍偏慢',summary:'焊料企业采购维持刚需，终端补库持续性尚需验证。',source:'LME',sourceUrl:'https://www.lme.com/Metals/Non-ferrous/LME-Tin',publishedAt:'2026-09-03T08:21:00+08:00',time:'08:21',impact:70,confidence:78,tags:['需求','库存']},
];
const fallbackEvents=(asset:Asset):Event[]=>{const sources:Record<Asset,{source:string;url:string;tags:string[]}>={
 黄金:{source:'CME Group',url:'https://www.cmegroup.com/markets/metals/precious/gold.html',tags:['宏观','资金流']},白银:{source:'CME Group',url:'https://www.cmegroup.com/markets/metals/precious/silver.html',tags:['工业需求','库存']},铜:{source:'CME Group',url:'https://www.cmegroup.com/markets/metals/base/copper.html',tags:['中国需求','库存']},锡:{source:'LME',url:'https://www.lme.com/Metals/Non-ferrous/LME-Tin',tags:['库存','供应']},原油:{source:'ICE',url:'https://www.theice.com/products/219/Crude-Oil',tags:['供给','地缘']},美元:{source:'FRED',url:'https://fred.stlouisfed.org/series/DTWEXBGS',tags:['美元','利率']},大豆:{source:'CME Group',url:'https://www.cmegroup.com/markets/agricultural/grains/soybean.html',tags:['天气','库存']},玉米:{source:'CME Group',url:'https://www.cmegroup.com/markets/agricultural/grains/corn.html',tags:['天气','产量']},螺纹钢:{source:'SHFE',url:'https://www.shfe.com.cn/',tags:['基建','库存']}}; const p=sources[asset]; const base=900+Object.keys(assets).indexOf(asset)*2; return [
 {id:base,asset,side:'利多',title:`${asset}：资金与供需信号出现改善`,summary:`当前没有接入该品种的专属新闻流，先用${asset}通用供需与资金模板输出；接入 Provider 后会自动替换为真实事件。`,source:p.source,sourceUrl:p.url,publishedAt:'2026-09-03T10:18:00+08:00',time:'10:18',impact:64,confidence:58,tags:p.tags},
 {id:base+1,asset,side:'利空',title:`${asset}：宏观与库存验证尚未完成`,summary:`价格信号仍需结合库存、持仓和主力合约结构确认，暂不建议仅凭单一指标追单。`,source:p.source,sourceUrl:p.url,publishedAt:'2026-09-03T09:36:00+08:00',time:'09:36',impact:57,confidence:56,tags:['验证中','风控']},
 ];};
const strategy: Record<Asset,string[]> = {
 黄金:['回踩 2,638–2,645 分批试多','持有多单，2,632 下方止损','数据日前减仓 30%','突破 2,672 再顺势跟进','逢高锁定部分利润','周末风险敞口降至 50%','复盘资金流与下周事件'],
 白银:['31.20 附近轻仓试多','站稳 31.70 后加仓','关注金银比回落信号','波动扩大时上移止损','32.30 附近分批止盈','避免隔夜重仓','等待库存验证后决策'],
 锡:['观望，关注 254,000 支撑','支撑确认后小仓试多','若跌破支撑转为防守','关注产区供应消息','突破 260,000 再加仓','高位减仓控制回撤','等待下游订单数据'],
 铜:['回踩 9,760 附近观察','站稳 9,900 后顺势跟随','关注中国需求数据','库存累积时减仓','突破 10,050 再加仓','周末前降低杠杆','复核美元与制造业 PMI'],
 原油:['反弹 79.20 附近减仓','跌破 77.60 先防守','关注 OPEC+ 供给信号','库存意外累库止损收紧','站稳 80.00 再转多','避免事件前重仓','复盘裂解价差'],
 美元:['103.00 附近观察支撑','站稳 103.80 再跟随','关注美国就业与通胀','实际利率上行时偏多美元','突破 104.20 再加仓','重大数据前降低杠杆','复核金银比与风险资产'],
 大豆:['1,010 附近轻仓观察','站稳 1,030 后跟随','关注天气与出口销售','天气改善时降低多单','突破 1,050 再加仓','数据日前减仓','等待 USDA 验证'],
 玉米:['410 附近观察支撑','站稳 420 后跟随','关注种植与天气','跌破 405 转防守','放量突破 430 再加仓','避免隔夜重仓','复核库存与出口'],
 螺纹钢:['3,420 附近观察','需求回升再试多','关注库存与基建','跌破 3,380 先防守','突破 3,520 再跟随','控制黑色系相关性','等待地产与基建数据'],
};
const days=['周一','周二','周三','周四','周五','周六','周日'];
const qualityChecks=['来源分级','跨源去重','影响评分','时效评分','置信度校准','观点版本化','新增/删除 diff','多空切换 diff','策略变更 diff','来源可追溯','宏观联动','技术融合','成交量/OI','波动率状态','金银比','事件时间轴','七日策略','仓位上限','止损规则','催化剂清单','风险清单','数据新鲜度','刷新去抖','缓存扩展点','移动端折叠','深色对比度','键盘焦点','错误恢复','API 健康检查','安全响应头','SEO 元数据','可观测性','事件窗口','提醒开关','时区明确','紧凑模式','来源健康','过期防护','导出路径','分享路径'];
const calendar=[['20:30','美国非农就业','高','黄金 / 白银'],['22:00','ISM 服务业 PMI','中','黄金 / 白银'],['明日 09:00','中国精炼锡库存','中','锡'],['明日 21:00','美联储官员讲话','高','黄金']];
const calendarForAsset=(asset:Asset)=>({黄金:[['20:30','美国非农就业','高','黄金'],['22:00','ISM 服务业 PMI','中','黄金'],['明日 21:00','美联储官员讲话','高','黄金']],白银:[['20:30','美国非农就业','高','白银'],['22:00','ISM 服务业 PMI','中','白银'],['明日 09:00','COMEX 白银库存','中','白银']],铜:[['明日 09:00','中国制造业 PMI','高','铜'],['明日 16:00','LME 铜库存','中','铜'],['明日 22:00','美国 ISM 制造业','中','铜']],锡:[['明日 09:00','中国精炼锡库存','中','锡'],['明日 16:00','LME 锡库存 / 仓单','高','锡'],['明日 21:00','美元指数复核','中','锡']],原油:[['22:30','EIA 原油库存','高','原油'],['明日 02:00','OPEC+ 供给观察','高','原油'],['明日 20:30','美国初请失业金','中','原油']],美元:[['20:30','美国非农就业','高','美元'],['22:00','ISM 服务业 PMI','中','美元'],['明日 21:00','美联储官员讲话','高','美元']],大豆:[['明日 20:30','美国出口销售','中','大豆'],['明日 22:00','美国天气模型更新','高','大豆'],['周五 00:00','USDA 供需窗口','高','大豆']],玉米:[['明日 20:30','美国出口销售','中','玉米'],['明日 22:00','种植区天气更新','高','玉米'],['周五 00:00','USDA 供需窗口','高','玉米']],螺纹钢:[['明日 09:00','钢材库存周报','高','螺纹钢'],['明日 10:00','基建与地产数据','中','螺纹钢'],['明日 15:00','现货成交复核','中','螺纹钢']]})[asset]||calendar;
const sourceHealth=[['GDELT','公开资讯 / 去重','在线'],['Alpha Vantage','现货 / 外汇 / 日频','Key 后'],['FRED','宏观日频','Key 后'],['CFTC','COT 持仓周频','在线']];
const weekEvents: WeekEvent[] = [
 {id:101,date:'2026-08-28',window:'过去7天',side:'利多',impact:'中',title:'美元与实际利率回落窗口',assets:'黄金 / 白银',why:'贵金属估值对实际利率敏感，回落通常改善多头风险收益比。',source:'FRED',sourceUrl:'https://fred.stlouisfed.org/series/DGS10'},
 {id:102,date:'2026-08-29',window:'过去7天',side:'利空',impact:'中',title:'COMEX 贵金属库存止降回升',assets:'白银',why:'可交割库存回补会缓解短期供应紧张，抑制追涨。',source:'CME Group',sourceUrl:'https://www.cmegroup.com/markets/metals/precious/silver.html'},
 {id:103,date:'2026-08-30',window:'过去7天',side:'利多',impact:'高',title:'避险情绪推升黄金资金流',assets:'黄金',why:'资金流与避险需求同向时，回撤更容易获得承接。',source:'CME Group',sourceUrl:'https://www.cmegroup.com/markets/metals/precious/gold.html'},
 {id:104,date:'2026-08-31',window:'过去7天',side:'利空',impact:'中',title:'电子终端补库延续性仍待验证',assets:'锡',why:'焊料刚需尚未转为主动补库，需求端对锡价形成上行约束。',source:'LME',sourceUrl:'https://www.lme.com/Metals/Non-ferrous/LME-Tin'},
 {id:105,date:'2026-09-01',window:'过去7天',side:'利多',impact:'高',title:'主要产区运输扰动预期升温',assets:'锡',why:'矿端审批与运输扰动可能收紧现货，低加工费放大价格弹性。',source:'SMM',sourceUrl:'https://news.metal.com/'},
 {id:106,date:'2026-09-02',window:'过去7天',side:'中性',impact:'中',title:'金银比高位震荡，风格尚未切换',assets:'黄金 / 白银',why:'金银比未确认下行前，白银的高弹性应匹配更低仓位。',source:'CME Group',sourceUrl:'https://www.cmegroup.com/markets/metals/precious/silver.html'},
 {id:107,date:'2026-09-03',window:'过去7天',side:'中性',impact:'高',title:'非农前的仓位再平衡窗口',assets:'黄金 / 白银',why:'重大数据前波动率常先抬升，优先控制隔夜尾部风险。',source:'BLS',sourceUrl:'https://www.bls.gov/schedule/news_release/empsit.htm'},
 {id:108,date:'2026-09-04',window:'未来7天',side:'中性',impact:'高',title:'美国非农就业报告（计划窗口）',assets:'黄金 / 白银',why:'就业与薪资决定降息预期，数据超预期偏利空贵金属，走弱则偏利多。',source:'BLS',sourceUrl:'https://www.bls.gov/schedule/news_release/empsit.htm'},
 {id:109,date:'2026-09-05',window:'未来7天',side:'中性',impact:'中',title:'中国精炼锡库存更新（计划窗口）',assets:'锡',why:'库存去化确认供应偏紧，累库则验证需求偏弱；以现货升贴水交叉验证。',source:'SMM',sourceUrl:'https://news.metal.com/'},
 {id:110,date:'2026-09-06',window:'未来7天',side:'中性',impact:'中',title:'CFTC COT 持仓报告跟踪',assets:'黄金 / 白银 / 锡',why:'净多变化用于识别拥挤度，不单独作为开仓信号。',source:'CFTC',sourceUrl:'https://publicreporting.cftc.gov/stories/s/r4w3-av2u'},
 {id:111,date:'2026-09-07',window:'未来7天',side:'中性',impact:'中',title:'美联储官员讲话密集窗口',assets:'黄金 / 白银',why:'措辞变化可能引发美元与实际利率的日内反转，需设置事件前后保护单。',source:'Federal Reserve',sourceUrl:'https://www.federalreserve.gov/newsevents/calendar.htm'},
 {id:112,date:'2026-09-08',window:'未来7天',side:'中性',impact:'中',title:'LME 锡库存与注销仓单变化',assets:'锡',why:'注销仓单上升且库存下降偏利多，反之则降低追多胜率。',source:'LME',sourceUrl:'https://www.lme.com/Metals/Non-ferrous/LME-Tin'},
 {id:113,date:'2026-09-09',window:'未来7天',side:'中性',impact:'中',title:'美国通胀预期与美元指数复核',assets:'黄金 / 白银',why:'实际利率、美元与金银价格的相关性若背离，提示趋势信号需要降权。',source:'FRED',sourceUrl:'https://fred.stlouisfed.org/series/DTWEXBGS'},
 {id:114,date:'2026-09-10',window:'未来7天',side:'中性',impact:'高',title:'周末前风险预算再平衡',assets:'黄金 / 白银 / 锡',why:'在数据与库存信号未完全确认前，将组合杠杆降至计划上限以内。',source:'期鉴风控规则',sourceUrl:'https://www.cmegroup.com/education/courses/introduction-to-futures/risk-management.html'},
];
const currentPlans: Record<Asset,{bias:string;action:string;trigger:string;invalid:string;size:string;next:string}> = {
 黄金:{bias:'回踩偏多',action:'回踩支撑区分批试多，突破前高再顺势加仓；不追事件前急拉。',trigger:'实际利率继续回落且价格站稳 2,660',invalid:'跌破 2,632 或非农显著超预期',size:'单品种风险 ≤ 0.5R，组合仓位 ≤ 40%',next:'非农就业 + 美元 / 实际利率'},
 白银:{bias:'震荡偏多',action:'只在 31.20 附近承接或放量站稳 31.70 后跟随，波动放大时减仓。',trigger:'金银比回落、库存未继续累积',invalid:'失守 31.00 或金价同步转弱',size:'单品种风险 ≤ 0.35R，仓位低于黄金',next:'COMEX 库存 + 金银比'},
 锡:{bias:'中性偏空',action:'等待 254,000 支撑确认；反弹靠近 260,000 先减仓，不在区间中部追单。',trigger:'库存去化与现货升水同时出现',invalid:'跌破 254,000 且下游订单无改善',size:'单品种风险 ≤ 0.25R，优先观望',next:'LME 库存 / 注销仓单 + 中国库存'},
 铜:{bias:'中性观察',action:'等待需求与库存同向确认，9,760 附近观察承接，避免在区间中部追价。',trigger:'中国制造业数据改善且库存去化',invalid:'美元走强、库存累积且跌破 9,760',size:'单品种风险 ≤ 0.3R，仓位 ≤ 30%',next:'中国 PMI + LME / COMEX 库存'},
 原油:{bias:'震荡偏空',action:'反弹减仓、破位防守；只有供给扰动与价格重新站上 80.00 才考虑转多。',trigger:'供给收缩且库存连续下降',invalid:'库存累积或跌破 77.60',size:'单品种风险 ≤ 0.3R，避免事件前重仓',next:'EIA 库存 + OPEC+ 会议'},
 美元:{bias:'中性观察',action:'围绕 102.60–104.20 做条件跟踪；数据走弱时降低美元多头，站稳阻力再顺势。',trigger:'实际利率上行且 DXY 站稳 103.80',invalid:'跌破 102.60 或就业数据明显转弱',size:'单品种风险 ≤ 0.25R，避免与贵金属方向重复',next:'美国就业 + 美债实际利率'},
 大豆:{bias:'中性观察',action:'天气与出口数据确认前轻仓；1,010 附近观察，突破 1,030 再跟随。',trigger:'天气恶化且出口销售改善',invalid:'天气改善、出口走弱且跌破 1,000',size:'单品种风险 ≤ 0.25R，仓位 ≤ 25%',next:'USDA 报告 + 美国天气'},
 玉米:{bias:'中性观察',action:'围绕 410–420 区间做条件单，产量与库存未确认前不追涨杀跌。',trigger:'天气扰动或出口销售超预期',invalid:'跌破 405 且库存预期上修',size:'单品种风险 ≤ 0.25R，优先区间交易',next:'USDA 供需 + 天气窗口'},
 螺纹钢:{bias:'中性偏空',action:'等待库存拐点和现货成交改善；反弹靠近 3,520 先减仓。',trigger:'库存连续去化且基建需求回升',invalid:'跌破 3,380 或库存重新累积',size:'单品种风险 ≤ 0.25R，控制黑色系相关性',next:'钢材库存 + 基建 / 地产数据'},
};
const fallbackWeekEvents=(asset:Asset):WeekEvent[]=>[{id:3000+Object.keys(assets).indexOf(asset)*2,date:'2026-09-02',window:'过去7天',side:'中性',impact:'中',title:`${asset}：历史数据窗口待补齐`,assets:asset,why:'该品种的专属事件日历尚未接入，先以价格、库存、持仓和宏观因子作为替代验证。',source:'期鉴 Provider',sourceUrl:'https://www.cmegroup.com/markets.html'},{id:3001+Object.keys(assets).indexOf(asset)*2,date:'2026-09-08',window:'未来7天',side:'中性',impact:'中',title:`${asset}：下周数据验证窗口`,assets:asset,why:'接入对应交易所或产业资讯 Provider 后，将自动替换为实际发布时间、影响方向和来源链接。',source:'期鉴 Provider',sourceUrl:'https://www.cmegroup.com/markets.html'}];
const benchmarkPlatforms=[
 {name:'TradingView',tag:'图表与提醒首选',url:'https://www.tradingview.com/',strength:'图表、指标、脚本、跨市场观察列表和多设备提醒完整。',tradeoff:'交易所实时行情通常需单独购买数据权限；研究深度依赖用户配置。',fit:'个人交易者 / 技术分析'},
 {name:'Bloomberg Terminal',tag:'机构研究与工作流标杆',url:'https://professional.bloomberg.com/products/bloomberg-terminal/',strength:'新闻、数据、宏观、研究、组合风险与执行工作流一体化。',tradeoff:'成本高、学习曲线陡，适合专业机构而非轻量使用。',fit:'机构 / 专业投研'},
 {name:'Barchart Trader',tag:'期货品种覆盖强',url:'https://www.barchart.com/trader',strength:'期货报价、合约参数、历史数据、新闻、图表和交易面板集中。',tradeoff:'实时数据与交易能力依赖订阅及经纪商，生态更偏北美市场。',fit:'期货交易者 / 商品研究'},
];
const officialFuturesLinks=[
 ['CME Group','COMEX 黄金 / 白银、成交量与持仓','https://www.cmegroup.com/'],
 ['LME','锡及有色金属价格、库存与仓单','https://www.lme.com/'],
 ['ICE','能源、软商品与金融期货','https://www.theice.com/'],
 ['CFTC','美国期货监管与 COT 持仓报告','https://www.cftc.gov/'],
 ['上期所 SHFE','上海黄金、白银、锡等期货','https://www.shfe.com.cn/'],
 ['郑商所 CZCE','白糖、棉花、PTA 等期货','https://www.czce.com.cn/'],
 ['大商所 DCE','铁矿石、豆粕、棕榈油等期货','https://www.dce.com.cn/'],
 ['中金所 CFFEX','股指、国债期货','https://www.cffex.com.cn/'],
];
const symbolMap:Record<Asset,string>={黄金:'gold',白银:'silver',铜:'copper',锡:'tin',原油:'crude',美元:'usd',大豆:'soybean',玉米:'corn',螺纹钢:'rebar'};
const snapshotLabel=(payload:Snapshot)=>{
 if(payload.data_mode==='spot_realtime') return '免费现货实时';
 if(payload.data_mode==='fx_realtime') return '免费外汇实时';
 if(payload.data_mode==='daily_reference') return '免费日频参考';
 if(payload.data_mode==='licensed_delayed_required') return '交易所授权待接入';
 if(payload.data_mode==='demo_fallback_no_key') return '免费源待配置 Key';
 if(payload.data_mode==='fallback_provider_error') return '免费源暂时异常';
 return '演示数据';
};
const isLiveMode=(payload?:Snapshot)=>Boolean(payload && ['spot_realtime','fx_realtime'].includes(payload.data_mode));
const formatSyncTime=(iso?:string)=>{if(!iso)return '等待同步'; const date=new Date(iso); if(Number.isNaN(date.getTime()))return '时间未知'; return new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(date)};
const quoteNumber=(value:string)=>Number(value.replace(/,/g,''));
const boardModeClass=(payload?:Snapshot)=>payload?isLiveMode(payload)?'live':payload.data_mode.startsWith('demo')||payload.data_mode==='fallback_provider_error'?'demo':payload.data_mode==='licensed_delayed_required'||payload.delayed?'delayed':'demo':'waiting';

export default function Home(){
 const [asset,setAsset]=useState<Asset>('黄金'); const [query,setQuery]=useState(''); const [dark,setDark]=useState(true);
 const [refresh,setRefresh]=useState(60); const [refreshTick,setRefreshTick]=useState(0); const [updated,setUpdated]=useState('刚刚'); const [beijingTime,setBeijingTime]=useState(''); const [toast,setToast]=useState(''); const [mobileNav,setMobileNav]=useState(false); const [filter,setFilter]=useState<'全部'|'已验证'|'变化'>('全部'); const [selected,setSelected]=useState<Event|null>(null); const [showQuality,setShowQuality]=useState(false); const [compact,setCompact]=useState(false); const [alerts,setAlerts]=useState(true); const [showCalendar,setShowCalendar]=useState(false); const [snapshot,setSnapshot]=useState<Snapshot|null>(null); const [globalQuotes,setGlobalQuotes]=useState<Snapshot[]>([]); const [dataStatus,setDataStatus]=useState('静态演示'); const [eventWindow,setEventWindow]=useState<'全部'|'过去7天'|'未来7天'>('全部'); const [imagePreview,setImagePreview]=useState(''); const [imageMeta,setImageMeta]=useState<ImageMeta|null>(null); const [imageAnalysis,setImageAnalysis]=useState<ImageAnalysis|null>(null); const [imageBusy,setImageBusy]=useState(false); const [imageStatus,setImageStatus]=useState<ImageStatus>('idle'); const [imageError,setImageError]=useState(''); const [searchOpen,setSearchOpen]=useState(false); const [syncStatus,setSyncStatus]=useState('等待同步'); const [lastSyncedAt,setLastSyncedAt]=useState(''); const [syncLatency,setSyncLatency]=useState<number|null>(null); const [syncError,setSyncError]=useState('');
 const imageRequestRef=useRef(0);
 const assetOptions=useMemo(()=>{const q=query.trim().toLowerCase(); const options=(Object.keys(assets) as Asset[]); return q?options.filter(x=>x.toLowerCase().includes(q)||assets[x].symbol.toLowerCase().includes(q)):options},[query]);
 const chooseAsset=(next:Asset)=>{setAsset(next);setQuery('');setSearchOpen(false);setMobileNav(false)};
 useEffect(()=>{const format=()=>setBeijingTime(new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date()).replace(/\//g,'-')); format(); const id=setInterval(format,1000); return()=>clearInterval(id)},[]);
 const currentEvents=events.some(e=>e.asset===asset)?events:fallbackEvents(asset);
 const filtered=useMemo(()=>currentEvents.filter(e=>e.asset===asset && (!query||e.title.includes(query)||e.summary.includes(query)||e.tags.some(t=>t.includes(query))) && (filter==='全部'||(filter==='已验证'&&e.confidence>=80)||(filter==='变化'&&e.id<=2))).sort((a,b)=>Date.parse(b.publishedAt)-Date.parse(a.publishedAt)),[asset,query,filter,currentEvents]);
 const timelineSource=weekEvents.some(e=>e.assets.includes(asset))?weekEvents:fallbackWeekEvents(asset);
 const timelineEvents=useMemo(()=>timelineSource.filter(e=>(eventWindow==='全部'||e.window===eventWindow)&&e.assets.includes(asset)).sort((a,b)=>Date.parse(a.date)-Date.parse(b.date)),[asset,eventWindow,timelineSource]);
 const doRefresh=()=>{setRefreshTick(t=>t+1);setUpdated('刚刚');setToast('已完成刷新 · 未发现重复资讯');setTimeout(()=>setToast(''),2500)};
 const flash=(message:string)=>{setToast(message);setTimeout(()=>setToast(''),2500)};
 const analyseImage=async(metaOverride?:ImageMeta, requestId=imageRequestRef.current)=>{const meta=metaOverride||imageMeta; if(!meta){flash('请先上传一张行情图或资讯截图');return} setImageBusy(true);setImageStatus('analyzing');setImageError(''); const apiBase=process.env.NEXT_PUBLIC_API_URL||''; try{const response=await fetch(`${apiBase}/api/v1/image-analysis`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...meta,asset})}); if(!response.ok)throw new Error('image analysis'); const result=await response.json() as ImageAnalysis; if(requestId===imageRequestRef.current){setImageAnalysis(result);setImageStatus('done')}}catch{if(requestId===imageRequestRef.current){setImageAnalysis({provider:'demo_vision',mode:'演示分析（离线回退）',title:`${asset} 图片结构已读取`,conclusion:`已读取 ${meta.file_name}（${meta.width}×${meta.height}），当前 ${asset} 研判为${assets[asset].tone}；图片分析建议与价格、成交量、持仓和事件窗口交叉验证。`,signals:['识别趋势线、支撑阻力与突破形态','检查图表周期、合约月份和时间戳','对照金银比 / 宏观数据确认是否背离'],next:'当前视觉 API 未连接，已展示本地演示结果；接入生产视觉模型后可返回 OCR、K 线形态、关键价位和图中标注解释。'});setImageStatus('done');setImageError('视觉服务未连接，已自动使用本地演示分析')}}finally{if(requestId===imageRequestRef.current)setImageBusy(false)}};
 const handleImage=(file:File|null)=>{if(!file)return; const lower=file.name.toLowerCase(); const isImage=file.type.startsWith('image/')||/\.(png|jpe?g|webp)$/i.test(lower); if(!isImage){flash('仅支持 PNG、JPG 或 WebP 图片');setImageStatus('error');setImageError('文件格式不受支持');return} if(file.size>8*1024*1024){flash('图片需小于 8MB');setImageStatus('error');setImageError('文件超过 8MB 限制');return} const requestId=++imageRequestRef.current; const preview=URL.createObjectURL(file); const meta:ImageMeta={file_name:file.name,mime_type:file.type||'image/jpeg',size_bytes:file.size,width:0,height:0}; setImagePreview(preview);setImageMeta(meta);setImageAnalysis(null);setImageError('');setImageStatus('loading'); const probe=new Image(); probe.onload=()=>{if(requestId!==imageRequestRef.current)return; const readyMeta={...meta,width:probe.naturalWidth,height:probe.naturalHeight};setImageMeta(readyMeta);setImageStatus('ready');void analyseImage(readyMeta,requestId)}; probe.onerror=()=>{if(requestId!==imageRequestRef.current)return;setImageStatus('error');setImageError('图片无法读取，请更换 PNG、JPG 或 WebP 文件');flash('图片读取失败，请重新选择')}; probe.src=preview};
 useEffect(()=>()=>{if(imagePreview)URL.revokeObjectURL(imagePreview)},[imagePreview]);
 useEffect(()=>{if(!refresh)return; const id=setInterval(doRefresh,refresh*1000);return()=>clearInterval(id)},[refresh]);
 const currentSymbol=symbolMap[asset];
 useEffect(()=>{let cancelled=false; const apiBase=process.env.NEXT_PUBLIC_API_URL||''; setSnapshot(null); fetch(`${apiBase}/api/v1/market/${currentSymbol}`).then(r=>{if(!r.ok)throw new Error('market');return r.json()}).then((payload:Snapshot)=>{if(!cancelled){setSnapshot(payload);setDataStatus(snapshotLabel(payload))}}).catch(()=>{if(!cancelled)setDataStatus('静态演示（API 未连接）')}); return()=>{cancelled=true}},[currentSymbol,refreshTick]);
 useEffect(()=>{let cancelled=false; const apiBase=process.env.NEXT_PUBLIC_API_URL||''; const started=performance.now(); setSyncStatus('同步中');setSyncError(''); fetch(`${apiBase}/api/v1/market/board`,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('board');return r.json()}).then(payload=>{if(cancelled)return; const sync=payload.sync as BoardSync|undefined;setGlobalQuotes(Array.isArray(payload.items)?payload.items:[]);setSyncLatency(typeof sync?.latency_ms==='number'?sync.latency_ms:Math.round(performance.now()-started));setLastSyncedAt(sync?.synced_at||new Date().toISOString());setSyncStatus('已同步')}).catch(()=>{if(!cancelled){setGlobalQuotes([]);setSyncLatency(Math.round(performance.now()-started));setSyncStatus('等待 API');setSyncError('交易数据接口未连接，当前看板保留演示值')}}); return()=>{cancelled=true}},[refreshTick]);
 const activeSnapshot=snapshot?.symbol===currentSymbol?snapshot:null;
 const active={price:activeSnapshot?.price?.toLocaleString('en-US',{maximumFractionDigits:3})||assets[asset].price,change:typeof activeSnapshot?.change_pct==='number'?`${activeSnapshot.change_pct>=0?'+':''}${activeSnapshot.change_pct.toFixed(2)}%`:'—'};
 const liveQuote=(name:Asset)=>globalQuotes.find(q=>q.symbol===symbolMap[name]);
 const quoteChange=(name:Asset)=>{const q=liveQuote(name); return typeof q?.change_pct==='number'?`${q.change_pct>=0?'+':''}${q.change_pct.toFixed(2)}%`:'—';};
 const boardQuote=(name:Asset):Snapshot=>liveQuote(name)||{symbol:symbolMap[name],name,price:quoteNumber(assets[name].price),change_pct:null,provider:'demo',data_mode:'demo_fallback',delayed:true,as_of:''};
 const boardLiveCount=focusAssets.filter(name=>isLiveMode(liveQuote(name))).length;
 const boardFreshness=syncStatus==='已同步'?(boardLiveCount?`${boardLiveCount}/6 实时源 · ${formatSyncTime(lastSyncedAt)}`:`已同步 · ${formatSyncTime(lastSyncedAt)}`):syncStatus;
 const refreshText=refresh<60?`每 ${refresh} 秒`:refresh===60?'每 1 分钟':`每 ${refresh/60} 分钟`;
 const currentPlan=currentPlans[asset];
 const currentCalendar=calendarForAsset(asset);
 const goldQuote=globalQuotes.find(q=>q.symbol==='gold')?.price||2654.8; const silverQuote=globalQuotes.find(q=>q.symbol==='silver')?.price||31.642; const goldSilverRatio=goldQuote/silverQuote; const ratioTone=goldSilverRatio>=85?'白银相对偏弱':goldSilverRatio<=75?'白银相对强势':'中性偏高'; const ratioAction=goldSilverRatio>=85?'黄金防守、白银等待比值回落再加仓':goldSilverRatio<=75?'白银弹性占优，黄金仓位需防相对落后':'等待比值确认方向，控制白银追涨仓位';
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.querySelector<HTMLInputElement>('.search input')?.focus()} if(e.key==='Escape')setSelected(null)};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[]);
 return <div className={`${dark?'app dark':'app'}${compact?' compact':''}`}>
  <header className="topbar"><button className="mobile-menu" onClick={()=>setMobileNav(!mobileNav)} aria-label="打开导航">☰</button><div className="brand"><span className="brand-mark">◆</span><div><b>期鉴</b><small>FUTURES INTELLIGENCE</small></div></div><label className="search"><span>⌕</span><input value={query} onFocus={()=>setSearchOpen(true)} onChange={e=>{setQuery(e.target.value);setSearchOpen(true)}} onKeyDown={e=>{if(e.key==='Enter'&&assetOptions[0])chooseAsset(assetOptions[0]);if(e.key==='Escape')setSearchOpen(false)}} placeholder="搜索其他品种、合约或关键词…"/><kbd>⌘ K</kbd>{searchOpen&&query&&<div className="search-results">{assetOptions.length?assetOptions.map(x=><button type="button" key={x} onMouseDown={e=>e.preventDefault()} onClick={()=>chooseAsset(x)}><span className={`mini-dot ${x===asset?'on':''}`}/><b>{x}</b><small>{assets[x].symbol}</small><em>切换分析</em></button>):<p>暂无匹配品种，可继续输入关键词筛选资讯</p>}</div>}</label><div className="top-actions"><span className="live"><i/>实时</span><button onClick={()=>setDark(!dark)} aria-label="切换主题">{dark?'☼':'◐'}</button><button className="avatar">Q</button></div></header>
  <aside className={mobileNav?'sidebar open':'sidebar'}><nav><span className="nav-label">工作台</span><a className="active" href="#overview">▦<b>市场总览</b></a><a href="#live-board">◈<b>实盘看板</b></a><a href="#intel">⌁<b>资讯雷达</b><em>12</em></a><a href="#changes">⌇<b>变化追踪</b><em className="orange">5</em></a><a href="#timeline">▥<b>策略日历</b></a><span className="nav-label">重点品种</span>{focusAssets.map((x,i)=><button key={x} className={asset===x?'asset active':'asset'} onClick={()=>{setAsset(x);setMobileNav(false)}}><span className={`dot d${i}`}/><b>{x}</b><small>{assets[x].symbol}</small></button>)}<span className="nav-label">工具</span><a href="#risk">⌗<b>风险中心</b></a><a href="#platforms">◎<b>平台对标</b></a><a href="#official">⚙<b>官方入口</b></a></nav><div className="system"><div><span>系统状态</span><b>全部正常</b></div><p><i/><span>数据延迟</span><b>1.2s</b></p><p><i/><span>来源在线</span><b>8 / 8</b></p></div></aside>
  <main><section id="overview" className="headline"><div><p className="eyebrow">市场情报中心 <span>北京时间 {beijingTime||'---- -- -- --:--:--'} · 实时</span></p><h1>{asset} <small>{assets[asset].symbol}</small></h1><p>聚合全球重要动态，结合宏观、技术与资金面生成可解释研判</p></div><div className="refresh"><span>更新于 {updated} · 延迟 1.2s</span><select value={refresh} onChange={e=>setRefresh(+e.target.value)} aria-label="自动刷新间隔"><option value="10">每 10 秒</option><option value="20">每 20 秒</option><option value="30">每 30 秒</option><option value="60">每 1 分钟</option><option value="180">每 3 分钟</option><option value="300">每 5 分钟</option><option value="600">每 10 分钟</option><option value="900">每 15 分钟</option><option value="1800">每 30 分钟</option><option value="3600">每 60 分钟</option></select><button onClick={doRefresh}>↻ 立即刷新</button><button className={alerts?'tool-active':''} onClick={()=>{setAlerts(!alerts);setToast(alerts?'已暂停事件提醒':'已开启事件提醒')}}>♧ {alerts?'提醒中':'提醒已停'}</button><button onClick={()=>setCompact(!compact)}>▤ {compact?'舒展':'紧凑'}</button></div></section>
   <section id="timeline" className="event-rail"><div className="rail-title"><span>事件日历</span><small>未来 24 小时 · 按影响排序</small></div>{currentCalendar.slice(0,3).map(c=><button key={c[0]} onClick={()=>setShowCalendar(true)}><b>{c[0]}</b><span>{c[1]}</span><em className={c[2]==='高'?'high':''}>{c[2]}</em><small>{c[3]}</small></button>)}<button className="rail-more" onClick={()=>setShowCalendar(!showCalendar)}>{showCalendar?'收起日历':'查看完整日历'} →</button></section>
   {showCalendar&&<section className="calendar-panel"><div className="calendar-head"><div><h2>高影响事件窗口 · {asset}</h2><p>用于管理持仓风险，时间均为上海时间</p></div><span>提醒 {alerts?'已开启':'已暂停'}</span></div><div className="calendar-grid">{currentCalendar.map(c=><div key={c[0]}><b>{c[0]}</b><div><strong>{c[1]}</strong><small>{c[3]}</small></div><em className={c[2]==='高'?'high':''}>{c[2]}影响</em></div>)}</div></section>}
   <section id="pulse" className="metrics"><div className="price-card"><span>主力参考价</span><div><strong>{active.price}</strong><b>{active.change}</b></div><small>参考区间 {assetContext[asset].range}</small><div className="spark"><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/></div></div><div><span>多空强度</span><strong className="amber">{assets[asset].score}</strong><b>/ 100 · {assets[asset].tone}</b><div className="bar"><i style={{width:`${assets[asset].score}%`}}/></div><small>较昨日 <em>↑ 6</em></small></div><div><span>关键事件</span><strong>{filtered.length||2}</strong><b>条高价值动态</b><small><em>▲ {filtered.filter(e=>e.side==='利多').length} 利多</em>　<span className="bear">▼ {filtered.filter(e=>e.side==='利空').length} 利空</span></small></div><div><span>研判置信度</span><strong>{Math.round(filtered.reduce((sum,e)=>sum+e.confidence,0)/(filtered.length||1))}%</strong><b>跨来源验证</b><small>{filtered.length?`${filtered.length} 条已纳入`:'等待数据'} · {dataStatus}</small></div></section>
   <section className="ratio-panel panel"><div className="ratio-main"><div><span>金银比 Gold / Silver</span><strong>{goldSilverRatio.toFixed(2)}</strong><small>黄金 {goldQuote.toLocaleString('en-US',{maximumFractionDigits:3})} ÷ 白银 {silverQuote.toLocaleString('en-US',{maximumFractionDigits:3})}</small></div><b className="ratio-badge">{ratioTone}</b></div><div className="ratio-meter"><i style={{width:`${Math.min(100,Math.max(0,(goldSilverRatio-60)*4))}%`}}/></div><div className="ratio-analysis"><div><span>趋势解读</span><p>比值上行：黄金相对占优、风险偏好偏弱；比值下行：白银相对占优、工业需求与风险偏好改善。</p></div><div><span>当前投资倾向</span><p>{ratioAction}</p></div><div><span>验证条件</span><p>结合美元、实际利率、COMEX / LME 库存与 CFTC 净持仓；金银比不单独作为开仓信号。</p></div></div></section>
   <section className={`image-lab panel ${imageStatus==='error'?'has-error':''}`}><div className="panel-head"><div><h2>图片辅助分析</h2><p>选择或拖入 K 线、持仓、库存或资讯截图后自动分析</p></div><span className="image-limit">PNG / JPG / WebP · ≤ 8MB · 仅本次分析</span></div><div className="image-lab-grid"><label className={`upload-box ${imageStatus}`} onDrop={e=>{e.preventDefault();handleImage(e.dataTransfer.files?.[0]||null)}} onDragOver={e=>e.preventDefault()}><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{handleImage(e.target.files?.[0]||null);e.currentTarget.value=''}}/><span className="upload-icon">＋</span><b>{imageMeta?'更换图片':'选择图片'}</b><small>{imageMeta?`${imageMeta.file_name} · ${(imageMeta.size_bytes/1024).toFixed(0)} KB`:'拖拽或点击上传，选择后自动开始分析'}</small><em>{imageStatus==='loading'?'读取图片…':imageStatus==='ready'?'已读取 · 自动分析中':imageStatus==='analyzing'?'分析中…':imageStatus==='done'?'分析完成':imageStatus==='error'?'读取失败':'等待上传'}</em></label>{imagePreview?<div className="image-preview"><img src={imagePreview} alt={`${asset} 待分析图片`} onLoad={e=>setImageMeta(prev=>prev?{...prev,width:e.currentTarget.naturalWidth,height:e.currentTarget.naturalHeight}:prev)} onError={()=>{setImageStatus('error');setImageError('图片预览加载失败，请重新选择文件')}}/><div><span>{imageMeta?.width&&imageMeta.height?`${imageMeta.width} × ${imageMeta.height}`:'读取尺寸中'}</span><button onClick={()=>analyseImage()} disabled={imageBusy}>{imageBusy?'分析中…':'重新分析'}</button></div></div>:<div className="image-empty"><span>⌁</span><p>上传后会立即显示缩略图、尺寸、识别状态和分析结果</p></div>}<div className={`image-result ${imageError?'has-error':''}`}>{imageBusy?<><div className="result-head"><b>正在分析 {imageMeta?.file_name||'图片'}</b><span>处理中</span></div><p className="image-loading">正在读取图表结构，请稍候…</p></>:imageAnalysis?<><div className="result-head"><b>{imageAnalysis.title}</b><span>{imageAnalysis.mode}</span></div><p>{imageAnalysis.conclusion}</p><ul>{imageAnalysis.signals.map(signal=><li key={signal}>✓ {signal}</li>)}</ul><small>{imageAnalysis.next}</small>{imageError&&<small className="image-note">{imageError}</small>}</>:imageError?<><div className="result-head"><b>图片分析未完成</b><span>请重试</span></div><p>{imageError}</p><small>请更换文件或点击“重新分析”；不会影响行情看板。</small></>:<p>分析结果将在这里显示。选择图片后会自动开始；当前无图片时不会上传任何内容。</p>}</div></div></section>
   <section className="compare-strip"><div className="compare-title"><span>跨品种速览</span><small>重点六品种 · {globalQuotes.length?'免费源同步':'等待 API'}</small></div>{focusAssets.map(x=><button key={x} className={x===asset?'chosen':''} onClick={()=>setAsset(x)}><span className={`mini-dot ${x===asset?'on':''}`}/><b>{x}</b><strong>{quoteChange(x)}</strong><small>{assets[x].tone}</small></button>)}<button className="quality-btn" onClick={()=>setShowQuality(!showQuality)}>质量门 {qualityChecks.length}/40　{showQuality?'收起':'展开'}</button></section>
   <section id="live-board" className="trade-board panel"><div className="panel-head"><div><h2>实盘交易看板</h2><p>重点六品种统一同步 · 实时/日频/授权状态分层显示</p></div><div className="board-actions"><span className={`sync-pill ${syncStatus==='已同步'?'ok':''}`}><i/>{syncStatus}</span><span className="sync-meta">{syncError||`${boardFreshness} · ${syncLatency===null?'—':`${syncLatency} ms`}`}</span><button onClick={doRefresh}>↻ 同步行情</button></div></div><div className="board-kpis"><div><span>可用实时源</span><strong>{boardLiveCount}<small>/ 6</small></strong><em>{boardLiveCount?'现货 / 外汇':'等待配置免费 Key'}</em></div><div><span>同步方式</span><strong>轮询</strong><em>{refreshText} · 服务端缓存 {15}s</em></div><div><span>数据纪律</span><strong>不伪装</strong><em>无授权行情显示为演示或待接入</em></div></div><div className="board-table-wrap"><table className="board-table"><thead><tr><th>品种</th><th>最新价</th><th>涨跌</th><th>数据状态</th><th>更新时间</th><th>来源</th></tr></thead><tbody>{focusAssets.map(name=>{const live=liveQuote(name);const quote=boardQuote(name);const hasApiRow=Boolean(live);const change=typeof quote.change_pct==='number'?`${quote.change_pct>=0?'+':''}${quote.change_pct.toFixed(2)}%`:hasApiRow?'—':assets[name].change;const mode=hasApiRow?snapshotLabel(quote):'API 未连接 · 演示值';return <tr key={name} className={name===asset?'selected-row':''} onClick={()=>setAsset(name)} tabIndex={0} onKeyDown={e=>e.key==='Enter'&&setAsset(name)}><td><span className="board-dot"/><b>{name}</b><small>{assets[name].symbol}</small></td><td className="board-price">{quote.price.toLocaleString('en-US',{maximumFractionDigits:3})}</td><td className={change.startsWith('-')?'negative':'positive'}>{change}</td><td><span className={`board-mode ${boardModeClass(quote)}`}><i/>{mode}</span></td><td>{hasApiRow&&quote.data_mode!=='demo_fallback_no_key'?formatSyncTime(quote.as_of):'—'}</td><td>{hasApiRow&&quote.source_url?<a href={quote.source_url} target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()}>来源 ↗</a>:<span className="muted-cell">—</span>}</td></tr>})}</tbody></table></div><div className="board-foot"><span><i className="live-dot"/>绿色“实时”仅代表 Provider 返回实时现货 / 外汇；铜、原油为日频参考，锡仍需交易所授权。</span><span>同步时间：{formatSyncTime(lastSyncedAt)} · {syncStatus}</span></div></section>
   {showQuality&&<section className="quality-panel"><div><b>本轮自检已覆盖 {qualityChecks.length} 项</b><p>基准：TradingView 的提醒与事件日历、CME 的成交量/持仓透明度、Bloomberg 的来源聚合与工作流。</p></div><div className="quality-grid">{qualityChecks.map((q,i)=><span key={q}><i>✓</i>{String(i+1).padStart(2,'0')} {q}</span>)}</div><div className="benchmark-links"><a href="https://www.tradingview.com/features/" target="_blank" rel="noreferrer">TradingView 能力参考 ↗</a><a href="https://www.cmegroup.com/market-data/volume-open-interest.html" target="_blank" rel="noreferrer">CME Volume/OI ↗</a><a href="https://professional.bloomberg.com/products/bloomberg-terminal/" target="_blank" rel="noreferrer">Bloomberg Terminal ↗</a></div></section>}
    <div className="content-grid"><section id="intel" className="panel intel"><div className="panel-head"><div><h2>今日情报雷达</h2><p>已去重并按影响力排序 · 每条资讯保留原始来源</p></div><div className="legend"><div className="filter-tabs">{(['全部','已验证','变化'] as const).map(x=><button key={x} className={filter===x?'selected':''} onClick={()=>setFilter(x)}>{x}</button>)}</div><span><i className="bull"/>利多</span><span><i className="bear-dot"/>利空</span></div></div><div className="side-columns">{(['利多','利空'] as const).map(side=><div key={side}><h3 className={side==='利多'?'bull-text':'bear'}>{side==='利多'?'▲ 利多驱动':'▼ 利空压力'} <span>{filtered.filter(e=>e.side===side).length}</span></h3>{filtered.filter(e=>e.side===side).map(e=><article className="event" key={e.id} onClick={()=>setSelected(e)} tabIndex={0} onKeyDown={ev=>ev.key==='Enter'&&setSelected(e)}><div className="event-meta"><span>{e.time}</span><b>{e.source}</b><em>影响 {e.impact}</em></div><h4>{e.title}</h4><p>{e.summary}</p><div className="tags">{e.tags.map(t=><span key={t}>{t}</span>)}</div><footer><span>置信度 <b>{e.confidence}%</b></span><a href={e.sourceUrl} target="_blank" rel="noreferrer" onClick={ev=>ev.stopPropagation()}>查看来源 ↗</a><span className="detail-hint">详情 ›</span></footer></article>)}</div>)}</div></section>
    <aside className="right-stack"><section className="panel pulse"><div className="panel-head"><div><h2>市场脉搏</h2><p>近 12 小时观点变化</p></div><span className="trend">+12%</span></div><div className="chart"><div className="gridlines"/><div className="area-shape"/><div className="line-shape"/><span className="marker m1">宏观</span><span className="marker m2">库存</span></div><div className="chart-axis"><span>22:00</span><span>02:00</span><span>06:00</span><span>10:00</span></div></section><section id="changes" className="panel changes"><div className="panel-head"><div><h2>最新变化</h2><p>相较上次刷新 · 可审计</p></div><button onClick={()=>setToast('变化日志已标记为已读')}>标记已读</button></div><ul><li><i className="new">新</i><div><b>新增宏观事件</b><p>{asset}数据窗口进入观察</p><small>2 分钟前 · <span className="green-text">added</span></small></div></li><li><i className="up">↗</i><div><b>观点由中性转为{assets[asset].tone}</b><p>价格与基本面信号待交叉验证</p><small>18 分钟前 · <span className="green-text">sentiment_changed</span></small></div></li><li><i className="adjust">调</i><div><b>策略区间调整</b><p>{currentPlan.invalid}</p><small>36 分钟前 · <span className="amber-text">strategy_adjusted</span></small></div></li></ul></section><section id="risk" className="panel risk-card"><div className="panel-head"><div><h2>风险与催化剂</h2><p>下一个需要盯住的变量</p></div><span className="risk-state">中等</span></div><div className="risk-list"><p><i className="catalyst"/><span><b>催化剂</b>　{assetContext[asset].catalyst}</span><strong>+↑</strong></p><p><i className="risk"/><span><b>风险</b>　{assetContext[asset].risk}</span><strong>−↓</strong></p><p><i className="neutral-dot"/><span><b>验证</b>　{assetContext[asset].verify}</span><strong>待定</strong></p></div></section></aside></div>
   <section id="strategy" className="panel week"><div className="panel-head"><div><h2>未来 7 日策略路径</h2><p>基于当前市场状态动态更新 · 仅供研究参考</p></div><div className="risk-badge">风险预算 <b>中等</b></div></div><div className="week-grid">{days.map((d,i)=><article key={d} className={i===0?'today':''}><span>{d}</span><b>{i===0?'今日':`9/${4+i}`}</b><i className={i<2?'bull':i<5?'neutral':'quiet'}/><p>{strategy[asset][i]}</p><small>{i===2?'⚡ 重要数据':'仓位 ≤ '+(i<4?'40%':'25%')}</small></article>)}</div></section><footer className="disclaimer"><span>数据来源：GDELT、Alpha Vantage、FRED、CFTC 等公开渠道 · Provider 状态以页面标注为准</span><b>风险提示：本平台内容不构成投资建议</b></footer>
  </main><div className="data-state-float"><i className={snapshot?'online':''}/><span>{dataStatus}</span><b>{active.price}</b></div>{toast&&<div className="toast">✓ {toast}</div>}{selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><section className="detail-modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)} aria-label="关闭">×</button><span className={selected.side==='利多'?'modal-side bull-text':'modal-side bear'}>{selected.side} · 影响 {selected.impact}/100</span><h2>{selected.title}</h2><p className="modal-summary">{selected.summary}</p><div className="explain"><div><span>来源可信度</span><b>高 · {selected.source}</b></div><div><span>跨源验证</span><b>{selected.confidence >= 80 ? '2 / 3 来源一致' : '待更多来源'}</b></div><div><span>时效评分</span><b>{selected.time} 发布 · 仍在窗口内</b></div><div><span>研判动作</span><b>{selected.side==='利多'?'回踩关注做多机会':'反弹减仓并收紧止损'}</b></div></div><a className="source-link" href={selected.sourceUrl} target="_blank" rel="noreferrer">打开原始资讯来源 ↗</a></section></div>}
 <section id="platforms" className="platform-compare panel"><div className="sources-intro"><div><h2>全球主流分析平台对标</h2><p>用于理解产品定位与取舍；官方能力页面可直接访问</p></div><span>3 家平台</span></div><div className="platform-grid">{benchmarkPlatforms.map((p,i)=><article key={p.name}><div className="platform-top"><span className={`platform-rank rank-${i+1}`}>0{i+1}</span><div><h3>{p.name}</h3><small>{p.tag}</small></div></div><p><b>优势：</b>{p.strength}</p><p><b>取舍：</b>{p.tradeoff}</p><footer><span>适合：{p.fit}</span><a href={p.url} target="_blank" rel="noreferrer">官方网址 ↗</a></footer></article>)}</div></section>
 <section className="event-index"><div className="sources-intro"><div><h2>资讯时间索引</h2><p>按发布时间从新到旧 · 时间为上海时间 · 点击可访问原始来源</p></div><span>{filtered.length} 条</span></div><div className="event-index-list">{filtered.map(e=><div key={`index-${e.id}`}><time dateTime={e.publishedAt}>{e.publishedAt.slice(0,16).replace('T',' ')} 上海</time><span className={e.side==='利多'?'bull-text':'bear'}>{e.side}</span><b>{e.title}</b><a href={e.sourceUrl} target="_blank" rel="noreferrer">{e.source} 原文 ↗</a></div>)}</div></section>
 <section className="week-impact panel"><div className="panel-head"><div><h2>过去 / 未来 7 日关键影响事件</h2><p>时间轴按日期排序；未来日期为计划窗口，发布后会用实际时间覆盖</p></div><div className="timeline-filter">{(['全部','过去7天','未来7天'] as const).map(x=><button key={x} className={eventWindow===x?'selected':''} onClick={()=>setEventWindow(x)}>{x}</button>)}</div></div><div className="timeline-list">{timelineEvents.map(e=><article className="timeline-item" key={e.id}><div className={`timeline-dot ${e.side==='利多'?'bull-side':e.side==='利空'?'bear-side':'neutral-side'}`}/><time dateTime={e.date}>{e.date.slice(5).replace('-','/')} · {e.window}</time><span className={e.side==='利多'?'bull-text':e.side==='利空'?'bear':'neutral-text'}>{e.side} · {e.impact}影响</span><div><h3>{e.title}</h3><p>{e.why}</p><small>影响品种：{e.assets}</small></div><a href={e.sourceUrl} target="_blank" rel="noreferrer">{e.source} 原文 ↗</a></article>)}</div></section>
 <section className="trade-now panel"><div className="panel-head"><div><h2>今日当下交易策略 · {asset}</h2><p>由多空强度、可用行情状态和事件窗口共同生成；仅供研究参考</p></div><span className={`mode-badge ${activeSnapshot?'has-data':''}`}>{activeSnapshot?snapshotLabel(activeSnapshot):'演示数据'}</span></div><div className="trade-grid"><div className="now-signal"><span>当前倾向</span><strong>{currentPlan.bias}</strong><b>{active.price}　{active.change}</b><small>多空强度 {assets[asset].score}/100 · {activeSnapshot?.provider||'demo'} · {activeSnapshot?.as_of?new Date(activeSnapshot.as_of).toLocaleString('zh-CN',{hour12:false}):'等待刷新'}</small></div><div><span>执行计划</span><p>{currentPlan.action}</p><small>触发：{currentPlan.trigger}</small></div><div><span>风控边界</span><p>{currentPlan.invalid}</p><small>仓位：{currentPlan.size}</small></div><div><span>下一催化剂</span><p>{currentPlan.next}</p><small>事件前后不追价，等待价格与数据共振</small></div></div><div className="data-note"><i/>行情状态：{dataStatus}。公开免费通道仅在其明确支持的品种上提供现货/外汇实时或日频参考；锡等交易所期货仍需授权行情，平台不会将演示值标为实盘。</div></section>
 <section className="data-coverage panel"><div className="sources-intro"><div><h2>全球期货数据覆盖</h2><p>优先展示可获取、可追溯且标注时效的数据；点击来源可核验</p></div><span>Provider 可替换</span></div><div className="coverage-grid"><a href="https://www.alphavantage.co/documentation/" target="_blank" rel="noreferrer"><b>黄金 / 白银</b><span>Alpha Vantage GOLD_SILVER_SPOT</span><em>免费 Key：现货实时</em></a><a href="https://www.alphavantage.co/documentation/" target="_blank" rel="noreferrer"><b>铜 / 原油</b><span>Alpha Vantage COPPER / WTI</span><em>免费 Key：日频参考</em></a><a href="https://www.alphavantage.co/documentation/" target="_blank" rel="noreferrer"><b>美元</b><span>Alpha Vantage USD/CNY 外汇</span><em>免费 Key：外汇实时</em></a><a href="https://www.lme.com/Metals/Non-ferrous/LME-Tin" target="_blank" rel="noreferrer"><b>锡</b><span>LME 官方库存与结算</span><em>需授权：非实时</em></a><a href="https://publicreporting.cftc.gov/stories/s/r4w3-av2u" target="_blank" rel="noreferrer"><b>CFTC COT</b><span>持仓周报，识别拥挤度</span><em>周频 · 免费</em></a><a href="https://fred.stlouisfed.org/docs/api/fred/" target="_blank" rel="noreferrer"><b>FRED 宏观</b><span>实际利率 / 美元 / 原油</span><em>日频 · 免费 Key</em></a></div></section>
   <section className="sources-panel"><div className="sources-intro"><div><h2>数据质量与来源状态</h2><p>延迟、完整性和许可状态在接入生产 Provider 后自动更新</p></div><span>4 个免费适配器</span></div><div className="source-grid">{sourceHealth.map(s=><div key={s[0]}><i/><b>{s[0]}</b><small>{s[1]}</small><strong>{s[2]}</strong></div>)}</div></section>
 <footer id="official" className="official-links"><div className="sources-intro"><div><h2>常用期货官方入口</h2><p>交易所、监管与持仓资料原站链接；行情许可请以各机构条款为准</p></div><span>官方来源</span></div><div className="official-grid">{officialFuturesLinks.map(([name,desc,url])=><a key={name} href={url} target="_blank" rel="noreferrer"><b>{name}</b><span>{desc}</span><em>访问官网 ↗</em></a>)}</div><small className="official-note">期鉴只聚合与解释公开信息，不代表任何交易所、数据商或经纪商；链接打开后请以官方页面为准。</small></footer>
 </div>
}
