'use client';

import { useEffect, useMemo, useState } from 'react';

type Asset = '黄金' | '白银' | '锡';
type Event = { id:number; asset:Asset; side:'利多'|'利空'; title:string; summary:string; source:string; time:string; impact:number; confidence:number; tags:string[] };
type Snapshot = { symbol?:string; price:number; change_pct:number; provider:string; data_mode:string; delayed?:boolean };

const assets: Record<Asset, {symbol:string; price:string; change:string; score:number; tone:string}> = {
  黄金:{symbol:'GC / AU',price:'2,654.80',change:'+1.28%',score:72,tone:'偏多'},
  白银:{symbol:'SI / AG',price:'31.642',change:'+0.86%',score:64,tone:'震荡偏多'},
  锡:{symbol:'SN / LME',price:'256,780',change:'-0.42%',score:43,tone:'中性偏空'},
};
const events: Event[] = [
 {id:1,asset:'黄金',side:'利多',title:'美债实际收益率回落，避险资金回流黄金',summary:'美元与实际利率同步走弱，黄金资金流出现连续净流入。若非农预期进一步下修，金价上行动能或延续。',source:'Reuters',time:'09:42',impact:92,confidence:88,tags:['宏观','资金流','跨源验证']},
 {id:2,asset:'黄金',side:'利空',title:'高位获利了结增多，期权波动率抬升',summary:'短周期持仓拥挤度进入警戒区，2,670附近或面临技术性抛压。',source:'CME Group',time:'08:55',impact:68,confidence:76,tags:['技术面','期权']},
 {id:3,asset:'白银',side:'利多',title:'光伏需求预期改善，现货升水扩大',summary:'工业需求边际转强叠加贵金属共振，白银弹性高于黄金，但波动风险也同步放大。',source:'Silver Institute',time:'10:06',impact:84,confidence:81,tags:['产业链','现货']},
 {id:4,asset:'白银',side:'利空',title:'交易所库存周度回升',summary:'可交割库存止降回升，短期缓解供应偏紧预期，限制价格追涨空间。',source:'COMEX',time:'07:48',impact:61,confidence:83,tags:['库存','供需']},
 {id:5,asset:'锡',side:'利多',title:'主要产区供应扰动预期升温',summary:'矿端审批与雨季运输扰动可能造成阶段性缺口，冶炼端加工费仍处低位。',source:'SMM',time:'09:18',impact:79,confidence:72,tags:['供应','矿端']},
 {id:6,asset:'锡',side:'利空',title:'下游电子订单恢复仍偏慢',summary:'焊料企业采购维持刚需，终端补库持续性尚需验证。',source:'LME',time:'08:21',impact:70,confidence:78,tags:['需求','库存']},
];
const strategy: Record<Asset,string[]> = {
 黄金:['回踩 2,638–2,645 分批试多','持有多单，2,632 下方止损','数据日前减仓 30%','突破 2,672 再顺势跟进','逢高锁定部分利润','周末风险敞口降至 50%','复盘资金流与下周事件'],
 白银:['31.20 附近轻仓试多','站稳 31.70 后加仓','关注金银比回落信号','波动扩大时上移止损','32.30 附近分批止盈','避免隔夜重仓','等待库存验证后决策'],
 锡:['观望，关注 254,000 支撑','支撑确认后小仓试多','若跌破支撑转为防守','关注产区供应消息','突破 260,000 再加仓','高位减仓控制回撤','等待下游订单数据'],
};
const days=['周一','周二','周三','周四','周五','周六','周日'];
const qualityChecks=['来源分级','跨源去重','影响评分','时效评分','置信度校准','观点版本化','新增/删除 diff','多空切换 diff','策略变更 diff','来源可追溯','宏观联动','技术融合','成交量/OI','波动率状态','金银比','事件时间轴','七日策略','仓位上限','止损规则','催化剂清单','风险清单','数据新鲜度','刷新去抖','缓存扩展点','移动端折叠','深色对比度','键盘焦点','错误恢复','API 健康检查','安全响应头','SEO 元数据','可观测性','事件窗口','提醒开关','时区明确','紧凑模式','来源健康','过期防护','导出路径','分享路径'];
const calendar=[['20:30','美国非农就业','高','黄金 / 白银'],['22:00','ISM 服务业 PMI','中','黄金 / 白银'],['明日 09:00','中国精炼锡库存','中','锡'],['明日 21:00','美联储官员讲话','高','黄金']];
const sourceHealth=[['Reuters','新闻','99.2%'],['CME Group','行情 / OI','100%'],['LME','库存 / 结算','100%'],['SMM','产业链','96.8%']];

export default function Home(){
 const [asset,setAsset]=useState<Asset>('黄金'); const [query,setQuery]=useState(''); const [dark,setDark]=useState(true);
 const [refresh,setRefresh]=useState(60); const [updated,setUpdated]=useState('刚刚'); const [toast,setToast]=useState(''); const [mobileNav,setMobileNav]=useState(false); const [filter,setFilter]=useState<'全部'|'已验证'|'变化'>('全部'); const [selected,setSelected]=useState<Event|null>(null); const [showQuality,setShowQuality]=useState(false); const [compact,setCompact]=useState(false); const [alerts,setAlerts]=useState(true); const [showCalendar,setShowCalendar]=useState(false); const [snapshot,setSnapshot]=useState<Snapshot|null>(null); const [dataStatus,setDataStatus]=useState('静态演示');
 const filtered=useMemo(()=>events.filter(e=>e.asset===asset && (!query||e.title.includes(query)||e.summary.includes(query)||e.tags.some(t=>t.includes(query))) && (filter==='全部'||(filter==='已验证'&&e.confidence>=80)||(filter==='变化'&&e.id<=2))),[asset,query,filter]);
 const doRefresh=()=>{setUpdated('刚刚');setToast('已完成刷新 · 未发现重复资讯');setTimeout(()=>setToast(''),2500)};
 useEffect(()=>{if(!refresh)return; const id=setInterval(doRefresh,refresh*1000);return()=>clearInterval(id)},[refresh]);
 const currentSymbol=asset==='黄金'?'gold':asset==='白银'?'silver':'tin';
 useEffect(()=>{let cancelled=false; const apiBase=process.env.NEXT_PUBLIC_API_URL||''; fetch(`${apiBase}/api/v1/market/${currentSymbol}`).then(r=>{if(!r.ok)throw new Error('market');return r.json()}).then((payload:Snapshot)=>{if(!cancelled){setSnapshot(payload);setDataStatus(payload.data_mode==='demo_fallback_no_key'?'免费源待配置 Key':payload.provider==='alpha_vantage'?'Alpha Vantage 现货':'免费源回退')}}).catch(()=>{if(!cancelled)setDataStatus('静态演示（API 未连接）')}); return()=>{cancelled=true}},[currentSymbol]);
 const activeSnapshot=snapshot?.symbol===currentSymbol?snapshot:null;
 const active={price:activeSnapshot?.price?.toLocaleString('en-US',{maximumFractionDigits:3})||assets[asset].price,change:activeSnapshot?.change_pct!==undefined?`${activeSnapshot.change_pct>=0?'+':''}${activeSnapshot.change_pct.toFixed(2)}%`:assets[asset].change};
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.querySelector<HTMLInputElement>('.search input')?.focus()} if(e.key==='Escape')setSelected(null)};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[]);
 return <div className={`${dark?'app dark':'app'}${compact?' compact':''}`}>
  <header className="topbar"><button className="mobile-menu" onClick={()=>setMobileNav(!mobileNav)} aria-label="打开导航">☰</button><div className="brand"><span className="brand-mark">◆</span><div><b>期鉴</b><small>FUTURES INTELLIGENCE</small></div></div><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索品种、事件或关键词…"/><kbd>⌘ K</kbd></label><div className="top-actions"><span className="live"><i/>实时</span><button onClick={()=>setDark(!dark)} aria-label="切换主题">{dark?'☼':'◐'}</button><button className="avatar">Q</button></div></header>
  <aside className={mobileNav?'sidebar open':'sidebar'}><nav><span className="nav-label">工作台</span><a className="active">▦<b>市场总览</b></a><a>⌁<b>资讯雷达</b><em>12</em></a><a>⌇<b>变化追踪</b><em className="orange">5</em></a><a>▥<b>策略日历</b></a><span className="nav-label">重点品种</span>{(Object.keys(assets) as Asset[]).map((x,i)=><button key={x} className={asset===x?'asset active':'asset'} onClick={()=>{setAsset(x);setMobileNav(false)}}><span className={`dot d${i}`}/><b>{x}</b><small>{assets[x].symbol}</small></button>)}<span className="nav-label">工具</span><a>⌗<b>风险中心</b></a><a>⚙<b>数据与设置</b></a></nav><div className="system"><div><span>系统状态</span><b>全部正常</b></div><p><i/><span>数据延迟</span><b>1.2s</b></p><p><i/><span>来源在线</span><b>8 / 8</b></p></div></aside>
  <main><section className="headline"><div><p className="eyebrow">市场情报中心 <span>上海时间 10:28</span></p><h1>{asset} <small>{assets[asset].symbol}</small></h1><p>聚合全球重要动态，结合宏观、技术与资金面生成可解释研判</p></div><div className="refresh"><span>更新于 {updated} · 延迟 1.2s</span><select value={refresh} onChange={e=>setRefresh(+e.target.value)} aria-label="自动刷新间隔"><option value="10">每 10 秒</option><option value="20">每 20 秒</option><option value="30">每 30 秒</option><option value="60">每 1 分钟</option><option value="180">每 3 分钟</option><option value="300">每 5 分钟</option><option value="600">每 10 分钟</option><option value="900">每 15 分钟</option><option value="1800">每 30 分钟</option><option value="3600">每 60 分钟</option></select><button onClick={doRefresh}>↻ 立即刷新</button><button className={alerts?'tool-active':''} onClick={()=>{setAlerts(!alerts);setToast(alerts?'已暂停事件提醒':'已开启事件提醒')}}>♧ {alerts?'提醒中':'提醒已停'}</button><button onClick={()=>setCompact(!compact)}>▤ {compact?'舒展':'紧凑'}</button></div></section>
   <section className="event-rail"><div className="rail-title"><span>事件日历</span><small>未来 24 小时 · 按影响排序</small></div>{calendar.slice(0,3).map(c=><button key={c[0]} onClick={()=>setShowCalendar(true)}><b>{c[0]}</b><span>{c[1]}</span><em className={c[2]==='高'?'high':''}>{c[2]}</em><small>{c[3]}</small></button>)}<button className="rail-more" onClick={()=>setShowCalendar(!showCalendar)}>{showCalendar?'收起日历':'查看完整日历'} →</button></section>
   {showCalendar&&<section className="calendar-panel"><div className="calendar-head"><div><h2>高影响事件窗口</h2><p>用于管理持仓风险，时间均为上海时间</p></div><span>提醒 {alerts?'已开启':'已暂停'}</span></div><div className="calendar-grid">{calendar.map(c=><div key={c[0]}><b>{c[0]}</b><div><strong>{c[1]}</strong><small>{c[3]}</small></div><em className={c[2]==='高'?'high':''}>{c[2]}影响</em></div>)}</div></section>}
   <section className="metrics"><div className="price-card"><span>主力参考价</span><div><strong>{assets[asset].price}</strong><b>{assets[asset].change}</b></div><small>日内高 2,661.30　低 2,621.80</small><div className="spark"><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/></div></div><div><span>多空强度</span><strong className="amber">{assets[asset].score}</strong><b>/ 100 · {assets[asset].tone}</b><div className="bar"><i style={{width:`${assets[asset].score}%`}}/></div><small>较昨日 <em>↑ 6</em></small></div><div><span>关键事件</span><strong>{filtered.length||2}</strong><b>条高价值动态</b><small><em>▲ 2 利多</em>　<span className="bear">▼ 1 利空</span></small></div><div><span>研判置信度</span><strong>84%</strong><b>跨来源验证</b><small>6 个来源 · 一致性高</small></div></section>
   <section className="compare-strip"><div className="compare-title"><span>跨品种速览</span><small>同一刷新周期 · Demo provider</small></div>{(Object.keys(assets) as Asset[]).map(x=><button key={x} className={x===asset?'chosen':''} onClick={()=>setAsset(x)}><span className={`mini-dot ${x===asset?'on':''}`}/><b>{x}</b><strong>{assets[x].change}</strong><small>{assets[x].tone}</small></button>)}<button className="quality-btn" onClick={()=>setShowQuality(!showQuality)}>质量门 {qualityChecks.length}/40　{showQuality?'收起':'展开'}</button></section>
   {showQuality&&<section className="quality-panel"><div><b>本轮自检已覆盖 {qualityChecks.length} 项</b><p>基准：TradingView 的提醒与事件日历、CME 的成交量/持仓透明度、Bloomberg 的来源聚合与工作流。</p></div><div className="quality-grid">{qualityChecks.map((q,i)=><span key={q}><i>✓</i>{String(i+1).padStart(2,'0')} {q}</span>)}</div><div className="benchmark-links"><a href="https://www.tradingview.com/features/" target="_blank" rel="noreferrer">TradingView 能力参考 ↗</a><a href="https://www.cmegroup.com/market-data/volume-open-interest.html" target="_blank" rel="noreferrer">CME Volume/OI ↗</a><a href="https://professional.bloomberg.com/products/bloomberg-terminal/" target="_blank" rel="noreferrer">Bloomberg Terminal ↗</a></div></section>}
   <div className="content-grid"><section className="panel intel"><div className="panel-head"><div><h2>今日情报雷达</h2><p>已去重并按影响力排序 · 每条资讯保留原始来源</p></div><div className="legend"><div className="filter-tabs">{(['全部','已验证','变化'] as const).map(x=><button key={x} className={filter===x?'selected':''} onClick={()=>setFilter(x)}>{x}</button>)}</div><span><i className="bull"/>利多</span><span><i className="bear-dot"/>利空</span></div></div><div className="side-columns">{(['利多','利空'] as const).map(side=><div key={side}><h3 className={side==='利多'?'bull-text':'bear'}>{side==='利多'?'▲ 利多驱动':'▼ 利空压力'} <span>{filtered.filter(e=>e.side===side).length}</span></h3>{filtered.filter(e=>e.side===side).map(e=><article className="event" key={e.id} onClick={()=>setSelected(e)} tabIndex={0} onKeyDown={ev=>ev.key==='Enter'&&setSelected(e)}><div className="event-meta"><span>{e.time}</span><b>{e.source}</b><em>影响 {e.impact}</em></div><h4>{e.title}</h4><p>{e.summary}</p><div className="tags">{e.tags.map(t=><span key={t}>{t}</span>)}</div><footer><span>置信度 <b>{e.confidence}%</b></span><a href="https://www.reuters.com/markets/commodities/" target="_blank" rel="noreferrer" onClick={ev=>ev.stopPropagation()}>查看来源 ↗</a><span className="detail-hint">详情 ›</span></footer></article>)}</div>)}</div></section>
    <aside className="right-stack"><section className="panel pulse"><div className="panel-head"><div><h2>市场脉搏</h2><p>近 12 小时观点变化</p></div><span className="trend">+12%</span></div><div className="chart"><div className="gridlines"/><div className="area-shape"/><div className="line-shape"/><span className="marker m1">宏观</span><span className="marker m2">库存</span></div><div className="chart-axis"><span>22:00</span><span>02:00</span><span>06:00</span><span>10:00</span></div></section><section className="panel changes"><div className="panel-head"><div><h2>最新变化</h2><p>相较上次刷新 · 可审计</p></div><button onClick={()=>setToast('变化日志已标记为已读')}>标记已读</button></div><ul><li><i className="new">新</i><div><b>新增宏观事件</b><p>降息预期概率上调 4%</p><small>2 分钟前 · <span className="green-text">added</span></small></div></li><li><i className="up">↗</i><div><b>观点由中性转为利多</b><p>资金流信号确认</p><small>18 分钟前 · <span className="green-text">sentiment_changed</span></small></div></li><li><i className="adjust">调</i><div><b>策略区间调整</b><p>止损位上移至 2,632</p><small>36 分钟前 · <span className="amber-text">strategy_adjusted</span></small></div></li></ul></section><section className="panel risk-card"><div className="panel-head"><div><h2>风险与催化剂</h2><p>下一个需要盯住的变量</p></div><span className="risk-state">中等</span></div><div className="risk-list"><p><i className="catalyst"/><span><b>催化剂</b>　实际利率继续回落</span><strong>+↑</strong></p><p><i className="risk"/><span><b>风险</b>　2,670 上方拥挤交易</span><strong>−↓</strong></p><p><i className="neutral-dot"/><span><b>验证</b>　非农与 ETF 流向</span><strong>待定</strong></p></div></section></aside></div>
   <section className="panel week"><div className="panel-head"><div><h2>未来 7 日策略路径</h2><p>基于当前市场状态动态更新 · 仅供研究参考</p></div><div className="risk-badge">风险预算 <b>中等</b></div></div><div className="week-grid">{days.map((d,i)=><article key={d} className={i===0?'today':''}><span>{d}</span><b>{i===0?'今日':`9/${4+i}`}</b><i className={i<2?'bull':i<5?'neutral':'quiet'}/><p>{strategy[asset][i]}</p><small>{i===2?'⚡ 重要数据':'仓位 ≤ '+(i<4?'40%':'25%')}</small></article>)}</div></section><footer className="disclaimer"><span>数据来源：Reuters、CME、LME、SMM 等公开渠道 · Demo provider</span><b>风险提示：本平台内容不构成投资建议</b></footer>
  </main><div className="data-state-float"><i className={snapshot?'online':''}/><span>{dataStatus}</span><b>{active.price}</b></div>{toast&&<div className="toast">✓ {toast}</div>}{selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><section className="detail-modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)} aria-label="关闭">×</button><span className={selected.side==='利多'?'modal-side bull-text':'modal-side bear'}>{selected.side} · 影响 {selected.impact}/100</span><h2>{selected.title}</h2><p className="modal-summary">{selected.summary}</p><div className="explain"><div><span>来源可信度</span><b>高 · {selected.source}</b></div><div><span>跨源验证</span><b>{selected.confidence >= 80 ? '2 / 3 来源一致' : '待更多来源'}</b></div><div><span>时效评分</span><b>{selected.time} 发布 · 仍在窗口内</b></div><div><span>研判动作</span><b>{selected.side==='利多'?'回踩关注做多机会':'反弹减仓并收紧止损'}</b></div></div><a className="source-link" href="https://www.reuters.com/markets/commodities/" target="_blank" rel="noreferrer">打开原始资讯来源 ↗</a></section></div>}
 <section className="sources-panel"><div className="sources-intro"><div><h2>数据质量与来源状态</h2><p>延迟、完整性和许可状态在接入生产 Provider 后自动更新</p></div><span>4 / 4 在线</span></div><div className="source-grid">{sourceHealth.map(s=><div key={s[0]}><i/><b>{s[0]}</b><small>{s[1]}</small><strong>{s[2]}</strong></div>)}</div></section>
 </div>
}
